package com.wkq.database.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "USER_INFO".
 */
@Entity
public class UserInfo {

    @NotNull
    private String UserName;

    @Id
    private String UserPhoneNum;

    @NotNull
    private String UserPwd;

    @NotNull
    private String UserIcon;
    private boolean IsLogout;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public UserInfo() {
    }

    public UserInfo(String UserPhoneNum) {
        this.UserPhoneNum = UserPhoneNum;
    }

    @Generated
    public UserInfo(String UserName, String UserPhoneNum, String UserPwd, String UserIcon, boolean IsLogout) {
        this.UserName = UserName;
        this.UserPhoneNum = UserPhoneNum;
        this.UserPwd = UserPwd;
        this.UserIcon = UserIcon;
        this.IsLogout = IsLogout;
    }

    @NotNull
    public String getUserName() {
        return UserName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserName(@NotNull String UserName) {
        this.UserName = UserName;
    }

    public String getUserPhoneNum() {
        return UserPhoneNum;
    }

    public void setUserPhoneNum(String UserPhoneNum) {
        this.UserPhoneNum = UserPhoneNum;
    }

    @NotNull
    public String getUserPwd() {
        return UserPwd;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserPwd(@NotNull String UserPwd) {
        this.UserPwd = UserPwd;
    }

    @NotNull
    public String getUserIcon() {
        return UserIcon;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserIcon(@NotNull String UserIcon) {
        this.UserIcon = UserIcon;
    }

    public boolean getIsLogout() {
        return IsLogout;
    }

    public void setIsLogout(boolean IsLogout) {
        this.IsLogout = IsLogout;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
